ywlist3-master/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :lists
  devise_for :users

  root 'lists#index'

  get 'tags/:tag', to: 'lists#index', as: :tag

end

ywlist3-master/app/models/list.rb
class List < ActiveRecord::Base

	validates :title, presence: true,
                    length: { minimum: 5 }

    acts_as_taggable # Alias for acts_as_taggable_on :tags
  	acts_as_taggable_on :skills, :interests

  	
end

ywlist3-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_tagger




end

ywlist3-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ywlist3-master/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :tag_cloud

  # require 'will_paginate/array' 
  
  def tag_cloud
    @tags = List.tag_counts_on(:tags).order('count desc').limit(20)
  end



  # GET /lists
  # GET /lists.json
  def index
    if params[:tag]
      @lists = List.tagged_with(params[:tag])
    else
      @lists = List.all
    end
    @lists = @lists.order(created_at: :desc).page(params[:page]).per(9)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :content, :tag_list)
    end
end

ywlist3-master/app/helpers/application_helper.rb
module ApplicationHelper
	  include ActsAsTaggableOn::TagsHelper

end

ywlist3-master/app/helpers/lists_helper.rb
module ListsHelper


end

ywlist3-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ywlist3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '鹦鹉学习首页', lists_path, class: "navbar-brand" %>
      <%= link_to ' 新建清单+', new_list_path, class: "navbar-brand btn btn-info"  %>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="搜索清单">
          </div>
          <button type="submit" class="btn btn-default">搜索</button>
        </form>
    </div>



    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <button type="button" class="btn btn-default navbar-btn navbar-right">退出</button>
            <% end %>
              <div class="navbar-right navbar-brand"><%= current_user.email %>&nbsp</div>
          <% else %>
              <%= link_to new_user_session_path do %>
                <button type="button" class="btn btn-default navbar-btn">登陆</button>
              <% end %>
              <%= link_to new_user_registration_path do %>
                <button type="button" class="btn btn-default navbar-btn">注册</button>
              <% end %>
          <% end %>
    </div><!-- /.navbar-collapse -->


  </div><!-- /.container-fluid -->
</nav>





<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>