jiehaoyun-master/hospital/urls.py
# coding:utf-8
from django.conf.urls import url 
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'hospital'
urlpatterns = [
	url(r'^$', views.HospitalListView.as_view(), name='hospital_list'),
	url(r'^hospital/(?P<hospital_id>[0-9]+)/$', views.HospitalDetailView.as_view(), name='hospital_detail'),
	url(r'^doctorlist/$', views.DoctorListView.as_view(), name='doctor_list'),
	url(r'^doctor/(?P<doctor_id>\d+)/$', views.DoctorDetailView.as_view(), name='doctor_detail'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jiehaoyun-master/jiehaoyun/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('hospital.urls')),
]

jiehaoyun-master/hospital/models.py
# coding:utf-8
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible


@python_2_unicode_compatible
class Doctor(models.Model):
	name = models.CharField(verbose_name=u"医生名字", max_length=300)
	name_en = models.CharField(verbose_name=u"医生英文名", max_length=300)
	face = models.ImageField(upload_to="doctor/face", verbose_name=u"医生头像")
	college = models.CharField(verbose_name=u"毕业大学", max_length=300)
	ctime = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

	class Meta:
		verbose_name = u"医生"
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name








@python_2_unicode_compatible
class Hospital(models.Model):
	name = models.CharField(verbose_name=u"医院名称", max_length=300)
	name_en = models.CharField(verbose_name=u"医院名称英文", max_length=300)
	logo = models.ImageField(upload_to="hospital/logo", verbose_name=u"医院logo")
	desc = models.CharField(max_length=500, verbose_name=u"医院简介")
	address = models.CharField(max_length=300, verbose_name=u"地点")
	project = models.CharField(verbose_name=u"项目",choices=(("ivf","IVF"),("egg","捐卵"),("sur","代孕"),("jj","捐精"),("fe","冻卵")), max_length=3)
	web = models.URLField(verbose_name=u"官方网站",max_length=100,default='')
	doctors = models.ManyToManyField(Doctor)
	ctime = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

	class Meta:
		verbose_name = u"医院"
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name

jiehaoyun-master/hospital/views.py
# coding:utf-8
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View 
from django.http import HttpResponse, HttpRequest
from .models import Hospital, Doctor

# Create your views here.
# 医院列表页
class HospitalListView(View):
	def get(self, request):
		all_hospital = Hospital.objects.all().order_by('-ctime')

		return render(request, 'hospital/hospital_list.html', {
			'all_hospital':all_hospital,
		})


class HospitalDetailView(View):
	def get(self, request, hospital_id):
		hospital = Hospital.objects.get(id=int(hospital_id))

		return render(request, 'hospital/hospital_detail.html', {
			'hospital':hospital,
			})


class DoctorListView(View):
	def get(self, request):
		all_doctor = Doctor.objects.all().order_by('-ctime')

		return render(request, 'hospital/doctor_list.html', {
			'all_doctor':all_doctor,
			})


class DoctorDetailView(View):
	def get(self, request, doctor_id):
		doctor = Doctor.objects.get(id=int(doctor_id))

		return render(request, 'hospital/doctor_detail.html', {
			'doctor':doctor,
			})

jiehaoyun-master/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}接好孕</title>
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="#">
	<script src="https://cdn.bootcss.com/jquery/3.2.1/core.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	{% block head %}{% endblock %}
</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">接好孕</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="/">首页 <span class="sr-only">(current)</span></a></li>
	        <li><a href="{% url 'hospital:hospital_list' %}">医院</a></li>
	        <li><a href="{% url 'hospital:doctor_list' %}">医生</a></li>

	      </ul>
	      
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<div class="main">
		{% block main %}{% endblock %}
	</div>
</body>
</html>

jiehaoyun-master/templates/hospital/doctor_detail.html
{% extends 'base.html' %}
{% block title %}医生详情页{% endblock %}
{% block head %}
	<link rel="stylesheet" href="#">
{% endblock %}

{% block main %}
	

<h1>{{ doctor.name }}</h1>
<span>{{ doctor.name_en }}</span>
<div class="row">
  <div class="col-md-8">
  	<p>{{ doctor.college }}</p>
  	<p>{{ doctor.hospital }}</p>
  </div>
  <div class="col-md-4">
  	<img src="/media/{{ doctor.face }}" alt="{{ doctor.name }}头像" class="avatar">
  </div>
</div>



<div>



{% endblock main %}


{% block js %}


{% endblock %}

jiehaoyun-master/templates/hospital/doctor_list.html
{% extends 'base.html' %}
{% block title %}首页{% endblock %}
{% block head %}
	<link rel="stylesheet" href="#">
{% endblock %}

{% block main %}
	
	<ul>
		{% for doctor in all_doctor %}
			<li>
				<p class="doctor-name"><a href="{% url 'hospital:doctor_detail' doctor.id %}">{{ doctor.name }}</a></p>
			</li>
		{% endfor %}


	</ul>

{% endblock %}

jiehaoyun-master/templates/hospital/hospital_detail.html
{% extends 'base.html' %}
{% block title %}医院详情页{% endblock %}
{% block head %}
	<link rel="stylesheet" href="#">
{% endblock %}

{% block main %}
	

<h1>{{ hospital.name }}</h1>
<span>{{ hospital.name_en }}</span>
<div class="row">
  <div class="col-md-8">
  	<p>{{ hospital.address }}</p>
  	<p>{{ hospital.project }}</p>
  	<p>{{ hospital.desc }}</p>
  	<p>{{ hospital.web }}</p>

  </div>
  <div class="col-md-4">
  	<img src="/media/{{ hospital.logo }}" alt="{{ hospital.name }}logo" class="avatar">
  </div>
</div>



<div>



{% endblock main %}


{% block js %}


{% endblock %}

jiehaoyun-master/templates/hospital/hospital_list.html
{% extends 'base.html' %}
{% block title %}首页{% endblock %}
{% block head %}
	<link rel="stylesheet" href="#">
{% endblock %}

{% block main %}
	
	<ul>
		{% for hospital in all_hospital %}
			<li>
				<p class="hospital-name"><a href="{% url 'hospital:hospital_detail' hospital.id %}">{{ hospital.name }}</a></p>
			</li>
		{% endfor %}


	</ul>

{% endblock %}