actorgogo-master/actorgogo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import xadmin

urlpatterns = [
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^xadmin/', include(xadmin.site.urls)),
    url(r'', include('yanji.urls')),
]

actorgogo-master/yanji/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.static import static
from django.conf.urls import url 
from django.conf import settings


from . import views

app_name = 'yanji'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^actor/$', views.ActorView.as_view(), name='actor_list'),
	url(r'^yanji/(?P<pk>[0-9]+)/$', views.YanjiDetailView.as_view(), name='detail'),
	url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
	url(r'^actor/ptitle/(?P<pk>[0-9]+)/$', views.ActorPtitleView.as_view(), name='act_ptitle_list'),
	url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
	url(r'^actor/(?P<pk>[0-9]+)/$', views.ActorDetailView.as_view(), name='actor'),
	url(r'^drama/$', views.DramaView.as_view(), name='drama_list'),
	url(r'^drama/(?P<pk>[0-9]+)/$', views.DramaDetailView.as_view(), name='drama'),
	url(r'^taici/$', views.TaiciView.as_view(), name='taici_list'),
	url(r'^taici/(?P<pk>[0-9]+)/$', views.TaiciDetailView.as_view(), name='taici'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actorgogo-master/yanji/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible

import django.utils.timezone as timezone



@python_2_unicode_compatible
class Category(models.Model):
	name = models.CharField(verbose_name='演技分类', max_length=100)

	def __str__(self):
		return self.name

	# def get_absolute_url(self):
	# 	return reverse('yanji:cate_list', kwargs={'pk':self.pk})

	class Meta():
		verbose_name = '演技分类'
		verbose_name_plural = verbose_name




@python_2_unicode_compatible
class Tag(models.Model):
	name = models.CharField(verbose_name='演技标签', max_length=100)


	def __str__(self):
		return self.name

	class Meta():
		verbose_name = '演技标签'
		verbose_name_plural = verbose_name




@python_2_unicode_compatible
class Ptitle(models.Model):
	name = models.CharField('演员职称', max_length=100, blank=True)
	ctime = models.DateTimeField(verbose_name='添加时间', null=True, default=timezone.now)

	def __str__(self):
		return self.name

	class Meta():
		verbose_name = '演员职称'
		verbose_name_plural = verbose_name



@python_2_unicode_compatible
class Actor(models.Model):
	name = models.CharField(verbose_name='演员', max_length=100)
	touxiang = models.FileField(verbose_name='头像', upload_to='yanyuan_tx/', null=True, blank=True)
	ctime = models.DateTimeField(verbose_name='添加时间', null=True, default=timezone.now)
	ptitle = models.ForeignKey(Ptitle, blank=True)


	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('yanji:act_detail', kwargs={'pk':self.pk})


	class Meta():
		verbose_name = '演员'
		verbose_name_plural = verbose_name

@python_2_unicode_compatible
class Movietype(models.Model):
	name = models.CharField(verbose_name='影视剧类型', max_length=100)
	ctime = models.DateTimeField(verbose_name='添加时间', null=True, default=timezone.now)

	def __str__(self):
		return self.name

	class Meta():
		verbose_name = '影视剧类型'
		verbose_name_plural = verbose_name	


@python_2_unicode_compatible
class Movietv(models.Model):
	movietype = models.ForeignKey(Movietype, blank=True, verbose_name='影视剧类型')
	name = models.CharField(verbose_name='影视剧名称', max_length=100)
	ctime = models.DateTimeField(verbose_name='添加时间', null=True, default=timezone.now)


	def __str__(self):
		return self.name

	class Meta():
		verbose_name = '影视剧'
		verbose_name_plural = verbose_name	



@python_2_unicode_compatible
class Dramatype(models.Model):
	name = models.CharField(verbose_name='剧本类型', max_length=100)
	ctime = models.DateTimeField(verbose_name='添加时间', null=True, default=timezone.now)

	def __str__(self):
		return self.name

	class Meta():
		verbose_name = '剧本类型'
		verbose_name_plural = verbose_name


@python_2_unicode_compatible
class Taici(models.Model):
	title = models.CharField(verbose_name='台词', max_length=100)
	movietv = models.ForeignKey(Movietv, verbose_name='影视剧')
	content = models.TextField(verbose_name='台词内容')
	ctime = models.DateTimeField(verbose_name='添加时间', null=True, default=timezone.now)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('yanji:taici_detail', kwargs={'pk':self.pk})

	class Meta():
		verbose_name = '台词'
		verbose_name_plural = verbose_name


@python_2_unicode_compatible
class Drama(models.Model):
	name = models.CharField(verbose_name='剧本', max_length=100)
	movietv = models.ForeignKey(Movietv, blank=True, verbose_name='影视剧', null=True)
	dramatype = models.ForeignKey(Dramatype, verbose_name='剧本类型')
	content = models.TextField(verbose_name='剧本内容')
	taici = models.ForeignKey(Taici, blank=True, verbose_name='台词', null=True)
	ctime = models.DateTimeField(verbose_name='添加时间', null=True, default=timezone.now)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('yanji:drama_detail', kwargs={'pk':self.pk})


	class Meta():
		verbose_name = '剧本'
		verbose_name_plural = verbose_name


@python_2_unicode_compatible
class Yanji(models.Model):
	STATUS_CHOICES = (
		('d', '草稿'),
		('p', '发表'),
	)
	status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES, default='p')
	actor = models.ManyToManyField(Actor, blank=True)
	title = models.CharField(verbose_name='标题', max_length=100)
	content = models.TextField(verbose_name='内容')
	category = models.ForeignKey(Category)
	tag = models.ManyToManyField(Tag, blank=True)
	movietv = models.ForeignKey(Movietv)
	fengmian = models.ImageField(verbose_name='封面图', upload_to='yanji_fengmian/', null=True, blank=True)
	video = models.URLField(verbose_name='视频地址', max_length=200, default='www.actorgogo.com')
	ctime = models.DateTimeField(verbose_name='添加时间', null=True, default=timezone.now)


	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('yanji:detail', kwargs={'pk':self.pk})


	class Meta():
		verbose_name = '演技'
		verbose_name_plural = verbose_name

actorgogo-master/yanji/views.py
# -*- coding: utf-8 -*-
import markdown

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Yanji, Category, Tag, Actor, Ptitle, Drama, Taici, Dramatype
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator



class IndexView(ListView):
	model = Yanji
	template_name = 'yanji/index.html'
	context_object_name = 'yanji_list'
	paginate_by = 6




class YanjiDetailView(DetailView):
	model = Yanji
	template_name = 'yanji/detail.html'
	context_object_name = 'yanji'

	# def get(self, request, *args, **kwargs):
	# 	response = super(YanjiDetailView, self).get(request, *args, **kwargs)
	# 	return response

	# def get_object(self, queryset=None):
	# 	yanji = super(YanjiDetailView, self).get_object(queryset=None)
	# 	return yanji

    # def get_context_data(self, **kwargs):
    #     # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
    #     # 还要把评论表单、post 下的评论列表传递给模板。
    #     context = super(YanjiDetailView, self).get_context_data(**kwargs)
    #     form = CommentForm()
    #     comment_list = self.object.comment_set.all()
    #     context.update({
    #         'form': form,
    #         'comment_list': comment_list
    #     })
    #     return context


class CategoryView(ListView):
	model = Yanji
	template_name = 'yanji/cate_list.html'
	context_object_name = 'yanji_list'

	def get_queryset(self):
		cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
		return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(ListView):
	model = Yanji
	template_name = 'yanji/tag_list.html'
	context_object_name = 'yanji_list'

	def get_queryset(self):
		tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
		return super(TagView, self).get_queryset().filter(tag=tag)




class ActorView(ListView):
	model = Yanji
	template_name = 'yanji/actor_list.html'
	context_object_name = 'actor_list'
	
	# def get_queryset(self):
	# 	Actor = get_object_or_404(Actor, pk=self.kwargs.get('pk'))
	# 	return super(ActorView, self).get_queryset().filter(actor=actor)


class ActorDetailView(DetailView):
	model = Actor
	template_name = 'yanji/actor_detail.html'
	context_object_name = 'actor'



class ActorPtitleView(ListView):
	model = Actor
	template_name = 'yanji/act_ptitle_list.html'
	context_object_name = 'actor_list'

	def get_queryset(self):
		ptitle = get_object_or_404(Ptitle, pk=self.kwargs.get('pk'))
		return super(PtitleView, self).get_queryset().filter(ptitle=ptitle)



class DramaView(ListView):
	model = Drama
	template_name = 'yanji/drama_list.html'
	context_object_name = 'drama_list'
	paginate_by = 10


class DramaDetailView(DetailView):
	model = Drama
	template_name = 'yanji/drama_detail.html'
	context_object_name = 'drama'


class TaiciView(ListView):
	model = Taici
	template_name = 'yanji/taici_list.html'
	context_object_name = 'taici_list'
	paginate_by = 10


class TaiciDetailView(DetailView):
	model = Taici
	template_name = 'yanji/taici_detail.html'
	context_object_name = 'taici'

actorgogo-master/templates/yanji/act_ptitle_list.html
{% extends 'base.html' %}
{% load yanji_tags %}



{% block main %}


	<h3>演技派 - {{ name }}</h3>
	<br><br>



	<div>
		<span><strong>分类:</strong></span>

		{% get_ptitles as ptitle_list %}
		<ul class="nav nav-pills">
			{% for ptitle in ptitle_list %}
			<li role="presentation">
			  <a href="#">{{ ptitle.name }}</a>
			</li>
			{% endfor %}
		</ul>

	</div>

<br>
	<div class="row">
		{% get_actors as actor_list %}
		{% for actor in actor_list %}
		  <div class="col-xs-6 col-md-3">
		    	<a class="thumbnail" href="{% url 'yanji:actor' actor.pk %}">
			      <img src="/upload/{{ actor.touxiang }}" alt="{{ actor.name }}">
			      <br>
			      <p>{{ actor.name }}</p>
		      </a>
		    
		  </div>
	  {% empty %}
			<div class="no-shuji">暂时无数据</div>
		{% endfor %}
	</div>
		


	{% if is_paginated %}
	<div class="pagination-simple">
	  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
	  {% if page_obj.has_previous %}
	    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
	  {% endif %}
	  <!-- 显示当前页面信息 -->
	  <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
	  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
	  {% if page_obj.has_next %}
	    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
	  {% endif %}
	</div>
	{% endif %}


{% endblock main %}

actorgogo-master/templates/yanji/actor_detail.html
{% extends 'base.html' %}



{% block main %}
<div class="col-md-8">

	<div class="crumb">
		<ol class="breadcrumb">
		  <li><a href="{% url 'yanji:index' %}">首页</a></li>
		  <li><a href="{% url 'yanji:actor_list' %}">演员</a></li>
		  <li class="active">{{ actor.name }}</li>
		</ol>
	</div>





	<h2 class="name">
		{{ actor.name }}
	</h2>
	<br>
	<div>
		<p>{{ actor.ptitle }}</p>
	</div>
	<div class="touxiang">
		<img src="/upload/{{ actor.touxiang }}" alt="{{ actor.name }}">
	</div>

	<br>
	<h4>演技视频：</h4>
	<div class="row">
		{% for yanji in yanji_list %}
		  <div class="col-xs-6 col-md-3">
		    	<a class="thumbnail" href="{{ tag.yanji.get_absolute_url }}">
			      <img src="/upload/{{ tag.yanji.fengmian }}" alt="{{ tag.yanji }}">
			      <br>
			      <p>{{ tag.yanji }}</p>
		      </a>
		    
		  </div>
	  {% empty %}
			<div class="no-fangji">暂时无视频</div>
		{% endfor %}
	</div>
	

	<br>
	<h4>介绍：</h4>


	<br>
	<h4>评论：</h4>

</div>
{% endblock main %}

actorgogo-master/templates/yanji/actor_list.html
{% extends 'base.html' %}
{% load yanji_tags %}



{% block main %}


	<h3>演技派 - 演员</h3>
	<br><br>



	<div>
		<span><strong>分类:</strong></span>

		{% get_ptitles as ptitle_list %}
		<ul class="nav nav-pills">
			{% for ptitle in ptitle_list %}
			<li role="presentation">
			  <a href="#">{{ ptitle.name }}</a>
			</li>
			{% endfor %}
		</ul>

	</div>

<br>
	<div class="row">
		{% get_actors as actor_list %}
		{% for actor in actor_list %}
		  <div class="col-xs-6 col-md-3">
		    	<a class="thumbnail" href="{% url 'yanji:actor' actor.pk %}">
			      <img class="actor_list_touxiang" src="/upload/{{ actor.touxiang }}" alt="{{ actor.name }}">
			      <br>
			      <p>{{ actor.name }}</p>
		      </a>
		    
		  </div>
	  {% empty %}
			<div class="no-shuji">暂时无数据</div>
		{% endfor %}
	</div>
		


	{% if is_paginated %}
	<div class="pagination-simple">
	  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
	  {% if page_obj.has_previous %}
	    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
	  {% endif %}
	  <!-- 显示当前页面信息 -->
	  <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
	  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
	  {% if page_obj.has_next %}
	    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
	  {% endif %}
	</div>
	{% endif %}


{% endblock main %}

actorgogo-master/templates/yanji/cate_list.html
{% extends 'base.html' %}
{% load yanji_tags %}



{% block main %}


	<h3>演技派 - {{ name }}</h3>
	<br><br>



	<div>
		<span><strong>分类:</strong></span>

		{% get_categories as category_list %}
		<ul class="nav nav-pills">
			{% for category in category_list %}
			<li role="presentation">
			  <a href="{% url 'yanji:category' category.pk %}">{{ category.name }}</a>
			</li>
			{% endfor %}
		</ul>

	</div>

<br>
	<div class="row">
		{% for yanji in yanji_list %}
		  <div class="col-xs-6 col-md-3">
		    	<a class="thumbnail" href="{{ yanji.get_absolute_url }}">
			      <img src="/upload/{{ yanji.fengmian }}" alt="{{ yanji.title }}">
			      <br>
			      <p>{{ yanji.title }}</p>
		      </a>
		    
		  </div>
	  {% empty %}
			<div class="no-fangji">暂时无视频</div>
		{% endfor %}
	</div>
		


	{% if is_paginated %}
	<div class="pagination-simple">
	  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
	  {% if page_obj.has_previous %}
	    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
	  {% endif %}
	  <!-- 显示当前页面信息 -->
	  <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
	  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
	  {% if page_obj.has_next %}
	    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
	  {% endif %}
	</div>
	{% endif %}


{% endblock main %}

actorgogo-master/templates/yanji/detail.html
{% extends 'base.html' %}



{% block main %}
<div class="col-md-8">

	<div class="crumb">
		<ol class="breadcrumb">
		  <li><a href="{% url 'yanji:index' %}">首页</a></li>
		  <li><a href="{% url 'yanji:index' %}">演技</a></li>
		  <li class="active">{{ yanji.title }}</li>
		</ol>
	</div>


	<!-- 16:9 aspect ratio -->
	<div class="embed-responsive embed-responsive-16by9">
	  <iframe class="embed-responsive-item" src="http://7xm73y.com1.z0.glb.clouddn.com/video/medical/3D%20Medical%20Animation%20-%20Congestive%20Heart%20Failure.mp4
	"></iframe>
	</div>



	<h2 class="name">
		{{ yanji.title }}
	</h2>
	<br>
	<div>
		<span>{{ yanji.ctime }}</span>
		<span><a href="{% url 'yanji:category' yanji.category.pk %}">{{ yanji.category }}</a></span>
	</div>
	
	<br>
	<div>标签：{{ yanji.tag }}</div>
	<br>
	<h4>演员：</h3>
	<div>{{ yanji.authors }}</div>
	<h4>详细内容：</h3>
	<div>{{ yanji.content }}</div>

	<br>


	<br>
	<h4>评论：</h4>

</div>
{% endblock main %}

actorgogo-master/templates/yanji/drama_detail.html
{% extends 'base.html' %}
{% load yanji_tags %}



{% block main %}
<div class="col-md-8">

	<div class="crumb">
		<ol class="breadcrumb">
		  <li><a href="{% url 'yanji:index' %}">首页</a></li>
		  <li><a href="{% url 'yanji:drama_list' %}">剧本</a></li>
		  <li class="active">{{ drama.name }}</li>
		</ol>
	</div>





	<h2 class="name">
		{{ drama.name }}
	</h2>
	<br>
	<div>
		<p>{{ drama.movietv }}</p>
		<p>{{ drama.dramatype }}</p>
	</div>
	<div class="content">
		{{ drama.content }}
	</div>

	<br>
	<h4>台词：</h4>
	<div class="row">
		{% get_taicis as taici_list %}

		{% for taici in taici_list %}
		    <a href="{% url 'yanji:taici' taici.pk %}">{{ drama.taici }}</a>
		{% empty %}
					<div class="no-actor">暂时无数据</div>
		{% endfor %} 
	</div>

	<br>
	<h4>评论：</h4>

</div>
{% endblock main %}

actorgogo-master/templates/yanji/drama_list.html
{% extends 'base.html' %}
{% load yanji_tags %}



{% block main %}


	<h3>演技派 - 剧本</h3>
	<br><br>



	<div>
		<span><strong>分类:</strong></span>

		{% get_dramatypes as dramatype_list %}
		<ul class="nav nav-pills">
			{% for dramatype in dramatype_list %}
			<li role="presentation">
			  <a href="#">{{ dramatype.name }}</a>
			</li>
			{% endfor %}
		</ul>

	</div>

<br>
	<div class="row">
		<div class="col-xs-12 col-md-8">
			{% for drama in drama_list %}
				<div class="panel panel-default">
					<a href="{% url 'yanji:drama' drama.pk %}">
					  <div class="panel-heading">
					  	<h3 class="panel-title">{{ drama.name }}</h3>
					  </div>
					</a>
					<div class="panel-body" style="height: 56px; overflow: hidden;">{{ drama.content }}...</div>		
				</div>
		  {% empty %}
				<div class="no-shuji">暂时无数据</div>
			{% endfor %}
		</div>
	</div>
		


	{% if is_paginated %}
	<div class="pagination-simple">
	  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
	  {% if page_obj.has_previous %}
	    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
	  {% endif %}
	  <!-- 显示当前页面信息 -->
	  <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
	  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
	  {% if page_obj.has_next %}
	    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
	  {% endif %}
	</div>
	{% endif %}


{% endblock main %}

actorgogo-master/templates/yanji/index.html
{% extends 'base.html' %}
{% load yanji_tags %}



{% block main %}


	<h3>人生如戏，全靠演技</h3>
	<br><br>



	<div>
		<span><strong>分类:</strong></span>

		{% get_categories as category_list %}
		<ul class="nav nav-pills">
			{% for category in category_list %}
			<li role="presentation">
				<a href="{% url 'yanji:category' category.pk %}">{{ category.name }}</a>
			  <!-- <a href="{{ category.get_absolute_url }}">{{ category.name }}</a> -->
			</li>
			{% endfor %}
		</ul>

	</div>

<br>
	<div class="row">
		{% for yanji in yanji_list %}
		  <div class="col-xs-6 col-md-3">
		    	<a class="thumbnail" href="{{ yanji.get_absolute_url }}">
			      <img src="/upload/{{ yanji.fengmian }}" alt="{{ yanji.title }}"/>
			      <br>
			      <p>{{ yanji.title }}</p>
		      </a>
		    
		  </div>
	  {% empty %}
			<div class="no-fangji">暂时无视频</div>
		{% endfor %}
	</div>

	<div>
		{% get_tags as tag_list %}
		<p>热门标签：</p>

		{% for tag in tag_list %}
		    <a href="{% url 'yanji:tag' tag.pk %}">{{ tag.name }}</a>
		{% endfor %}
	</div>
		


	<h3>国家一级演员</h3>
	<br><br>

	<div class="swiper-container">
			{% get_actors as actor_list %}
	    <div class="swiper-wrapper">
	    	{% for actor in actor_list %}	        
	        <a class="thumbnail" href="{% url 'yanji:actor' actor.pk %}">
	        	<div class="swiper-slide">
				      <img src="/upload/{{ actor.touxiang }}" alt="{{ actor.name }}"/>
				      <!-- <br> -->
				      <p>{{ actor.name }}</p>
				 </div>
			</a>	        
	        {% empty %}
				<div class="no-actor">暂时无数据</div>
			{% endfor %} 

	    </div>
	    <!-- 如果需要分页器 -->
	    <div class="swiper-pagination"></div>
	    
	    <!-- 如果需要导航按钮 -->
	    <div class="swiper-button-prev"></div>
	    <div class="swiper-button-next"></div>
	  

	</div>

	<h3>剧本</h3>
	<br><br>


	<div>
		{% get_dramas as drama_list %}

		{% for drama in drama_list %}
		    <a href="{% url 'yanji:drama' drama.pk %}">{{ drama.name }}</a>
		{% empty %}
					<div class="no-actor">暂时无数据</div>
		{% endfor %} 
	</div>




	<h3>台词</h3>
	<br><br>

	<div>
		{% get_taicis as taici_list %}

		{% for taici in taici_list %}
		    <a href="{% url 'yanji:taici' taici.pk %}">{{ taici.title }}</a>
		{% empty %}
					<div class="no-actor">暂时无数据</div>
		{% endfor %} 
	</div>


	<h3>资讯</h3>
	<br><br>



{% endblock main %}
<script>        
  var mySwiper = new Swiper ('.swiper-container', {
    direction: 'vertical',
    loop: true,
    
    // 如果需要分页器
    pagination: {
      el: '.swiper-pagination',
    },
    
    // 如果需要前进后退按钮
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    }，
    

  })        
</script>

actorgogo-master/templates/yanji/tag_list.html
{% extends 'base.html' %}
{% load yanji_tags %}



{% block main %}


	<h3>演技派 - {{ name }}</h3>
	<br><br>



	<div>
		<span><strong>分类:</strong></span>

		{% get_tags as tag_list %}
		<ul class="nav nav-pills">
			{% for tag in tag_list %}
			<li role="presentation">
			  <a href="{% url 'yanji:tag' tag.pk %}">{{ tag.name }}</a>
			</li>
			{% endfor %}
		</ul>

	</div>

<br>
	<div class="row">
		{% for yanji in yanji_list %}
		  <div class="col-xs-6 col-md-3">
		    	<a class="thumbnail" href="{{ yanji.get_absolute_url }}">
			      <img src="/upload/{{ yanji.fengmian }}" alt="{{ yanji.title }}">
			      <br>
			      <p>{{ yanji.title }}</p>
		      </a>
		    
		  </div>
	  {% empty %}
			<div class="no-fangji">暂时无视频</div>
		{% endfor %}
	</div>
		


	{% if is_paginated %}
	<div class="pagination-simple">
	  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
	  {% if page_obj.has_previous %}
	    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
	  {% endif %}
	  <!-- 显示当前页面信息 -->
	  <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
	  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
	  {% if page_obj.has_next %}
	    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
	  {% endif %}
	</div>
	{% endif %}


{% endblock main %}

actorgogo-master/templates/yanji/taici_detail.html
{% extends 'base.html' %}



{% block main %}
<div class="col-md-8">

	<div class="crumb">
		<ol class="breadcrumb">
		  <li><a href="{% url 'yanji:index' %}">首页</a></li>
		  <li><a href="{% url 'yanji:taici_list' %}">台词</a></li>
		  <li class="active">{{ taici.title }}</li>
		</ol>
	</div>





	<h2 class="name">
		{{ taici.title }}
	</h2>
	<br>
	<div>
		<p>{{ taici.movietv }}</p>
		<p>{{ taici.ctime }}</p>
	</div>
	<div class="content">
		{{ taici.content }}
	</div>

	<br>
	<h4>评论：</h4>

</div>
{% endblock main %}

actorgogo-master/templates/yanji/taici_list.html
{% extends 'base.html' %}
{% load yanji_tags %}



{% block main %}


	<h3>演技派 - 台词</h3>
	<br><br>



	<div>
		<span><strong>分类:</strong></span>



	</div>

<br>
	<div class="row">
		<div class="col-xs-12 col-md-8">
			{% for taici in taici_list %}
				<div class="panel panel-default">
					<a href="{% url 'yanji:taici' taici.pk %}">
					  <div class="panel-heading">
					  	<h3 class="panel-title">{{ taici.title }}</h3>
					  </div>
					</a>
					<div class="panel-body" style="height: 56px; overflow: hidden;">{{ taici.content }}...</div>		
				</div>
		  {% empty %}
				<div class="no-shuji">暂时无数据</div>
			{% endfor %}
		</div>
	</div>
		


	{% if is_paginated %}
	<div class="pagination-simple">
	  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
	  {% if page_obj.has_previous %}
	    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
	  {% endif %}
	  <!-- 显示当前页面信息 -->
	  <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
	  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
	  {% if page_obj.has_next %}
	    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
	  {% endif %}
	</div>
	{% endif %}


{% endblock main %}